apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: vol1
          mountPath: /person
  volumes:
    - name: vol1
      configMap:
        name: person-details
  