apiVersion: v1
kind: PersistentVolume 
metadata: 
  name: file-store-01
spec: 
  capacity: 
    storage: 1Ti
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain 
  nfs:
    server: 10.10.85.42
    path: /vol01
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-store-vc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
    