apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-custom-sc
provisioner: kubernetes.io/gce-pd
volumeBindingMode: Immediate
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  type: pd-standard
  fstype: ext4
  replication-type: none